#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include "funcoes.h"

int main() {
  int rodar = 1;
  int programa;
  while (rodar) {
    system("clean");
    system("cls");
    printf("Escolha o programa a ser rodado:\n");
    printf("[1] = Multiplos de 3\n");
    printf("[2] = Contagem de 1 a 100\n");
    printf("[3] = Contagem regressiva\n");
    printf("[4] = Contagem de 1000 em 1000\n");
    printf("[5] = Soma de 10 numeros\n");
    printf("[6] = Media de 10 numeros\n");
    printf("[7] = Media de 10 numeros inteiros positivos\n");
    printf("[8] = Maior e menor valor digitado\n");
    printf("[9] = Numeros impares até N\n");
    printf("[10] = Soma dos primeiros 50 numeros pares\n");
    printf("[11] = Inteiros de 0 até N\n");
    printf("[12] = Inteiros de N até 0\n");
    printf("[13] = Naturais pares de 0 até N\n");
    printf("[14] = Naturais pares de N até 0\n");
    printf("[15] = Naturais impares de 0 até N\n");
    printf("[16] = Naturais impares de N até 0\n");
    printf("[17] = Soma dos naturais até N\n");
    printf("[18] = Quantas vezes o maior numero apareceu\n");
    printf("[19] = Algarismos de numero aleatorio\n");
    printf("[20] = Quantidade de pares e digitados\n");
    printf("[21] = Some os pares, multiplique os impares\n");
    printf("[22] = Calcule sua media\n");
    printf("[23] = Divisores de N\n");
    printf("[24] = Soma dos divisores de N\n");
    printf("[25] = Multiplos de 3 e 5 ate 1000\n");
    printf("[26] = Primeiro multiplo de 11, 13 ou 17\n");
    printf("[27] = Media harmonica\n");
    printf("[28] = Valor de E\n");
    printf("[29] = Valor de S\n");
    printf("[30] = Valor das sequencias\n");
    printf("[31] = Valor da sequencia S\n");
    printf("[32] = Lancamento de dois dados\n");
    printf("[33] = Multiplos i j de n\n");
    printf("[34] = Divisiveis em comum entre 1 e 20\n");
    printf("[35] = Soma dos impares entre X e Y\n");
    printf("[36] = Diferença da soma dos quadrados com o quadrado da soma\n");
    printf("[37] = Coincidencia ao quadrado\n");
    printf("[38] = O termo pitagorico\n");
    printf("[39] = Area do triangulo\n");
    printf("[40] = Maior termo digitado 2\n");
    printf("[41] = Calcular a resistencia 2\n");
    printf("[42] = Calcular quadrado, cubo e raiz\n");
    printf("[43] = Media de idades\n");
    printf("[44] = O fibonacci\n");
    printf("[45] = Conversao\n");
    printf("[46] = Jogo da Adivinhacao\n");
    printf("[47] = Calculadora\n");
    printf("[48] = Soma do fibonacci\n");
    printf("[49] = Caderneta de carlos\n");
    printf("[50] = Chico e ze\n");
    printf("[51] = Aumento de salario\n");
    printf("[52] = Saque bancario\n");
    printf("[53] = Triangulo de floyd\n");
    printf("[54] = Verifica o primo\n");
    printf("[55] = Soma os N primeiros primos\n");
    printf("[56] = Soma os primos até 2000000\n");
    printf("[57] = Quantidade de primos entre X e Y\n");
    printf("[58] = Soma de primos entre X e Y\n");
    printf("[59] = Consumo do mes\n");
    printf("[60] = Calcular soma, quantidade, media, maior, menor e media dos pares\n");
    printf("[61] = Maior palindromo\n");
    printf("[62] = Soma de numero por extenso\n");

    printf("[-1] = Sair\n");
    printf("Escolha: ");
    scanf("%d", &programa);

    switch (programa) {
      case 1: multiplos_de_3();
              system("pause");
              break;
      case 2: um_a_cem();
              system("pause");
              break;
      case 3: contagem_regressiva();
              system("pause");
              break;
      case 4: mil_em_mil();
              system("pause");
              break;
      case 5: soma_tudo();
              system("pause");
              break;
      case 6: media_inteiros();
              system("pause");
              break;
      case 7: media_inteiros_positivos();
              system("pause");
              break;
      case 8: maior_menor_valor();
              system("pause");
              break;
      case 9: impares_naturais();
              system("pause");
              break;
      case 10: soma_primeiros_50_pares();
               system("pause");
               break;
      case 11: naturais_ate_n();
               system("pause");
               break;
      case 12: naturais_de_n_a_zero();
               system("pause");
               break;
      case 13: naturais_pares_ate_n();
               system("pause");
               break;
      case 14: naturais_par_de_n_a_zero();
               system("pause");
               break;
      case 15: naturais_impares_ate_n();
               system("pause");
               break;
      case 16: naturais_impar_de_n_a_zero();
               system("pause");
               break;
      case 17: soma_naturais_ate_n();
               system("pause");
               break;
      case 18: maior_apareceu_x();
               system("pause");
               break;
      case 19: algarismos_aleatorios();
               system("pause");
               break;
      case 20: dados_de_numeros();
               system("pause");
               break;
      case 21: soma_multiplica_determinado();
               system("pause");
               break;
      case 22: notas_infinitas();
               system("pause");
               break;
      case 23: os_divisores();
               system("pause");
               break;
      case 24: soma_dos_divisores();
               system("pause");
               break;
      case 25: soma_multiplos_de_35_ate_1000();
               system("pause");
               break;
      case 26: primeiro_multiplo_de_XYZ();
               system("pause");
               break;
      case 27: media_harmonica();
               system("pause");
               break;
      case 28: valor_de_E();
               system("pause");
               break;
      case 29: valor_de_S();
               system("pause");
               break;
      case 30: valor_de_sequencias();
               system("pause");
               break;
      case 31: valor_da_sequencia_S();
               system("pause");
               break;
      case 32: dois_dados();
               system("pause");
               break;
      case 33: primeiros_naturais_multiplos_ij();
               system("pause");
               break;
      case 34: menos_numero_divisivel();
               system("pause");
               break;
      case 35: soma_impares_x_y();
               system("pause");
               break;
      case 36: soma_dos_qd_qd_da_soma();
               system("pause");
               break;
      case 37: matemagica();
               system("pause");
               break;
      case 38: termo_pitagorico();
               system("pause");
               break;
      case 39: area_do_triangulo();
               system("pause");
               break;
      case 40: maior_menor_valor_2();
               system("pause");
               break;
      case 41: calculo_resistencia();
               system("pause");
               break;
      case 42: qdr_cub_raiz();
               system("pause");
               break;
      case 43: media_idades();
               system("pause");
               break;
      case 44: fibonacci();
               system("pause");
               break;
      case 45: conversao();
               system("pause");
               break;
      case 46: adivinhacao();
               system("pause");
               break;
      case 47: caluladora();
               system("pause");
               break;
      case 48: fibonacci_soma();
               system("pause");
               break;
      case 49: carlos();
               system("pause");
               break;
      case 50: chico_e_ze();
               system("pause");
               break;
      case 51: aumento_salarial();
               system("pause");
               break;
      case 52: saque_bancario();
               system("pause");
               break;
      case 53: floyd_triangular();
               system("pause");
               break;
      case 54: verifica_primo();
               system("pause");
               break;
      case 55: soma_primeiros_primos();
               system("pause");
               break;
      case 56: soma_primos_ate_2000000();
               system("pause");
               break;
      case 57: primos_entre_xy();
               system("pause");
               break;
      case 58: soma_primos_entre_xy();
               system("pause");
               break;
      case 59: consumo_no_mes();
               system("pause");
               break;
      case 60: soma_qtd_med_ma_me_par();
               system("pause");
               break;
      case 61: Maior_Palindromo();
               system("pause");
               break;
      case 62: Soma_Caractere_Num_extenso();
               system("pause");
               break;

      case -1: rodar = 0;
               break;
      default: printf("PROGRAMA INEXISTENTE\n");
    }
  }
  return 0;
}
