CREATE TABLE DEPARTAMENTO(
    DEP_COD NUMBER(4) PRIMARY KEY,
    DEP_DECRICAO VARCHAR(20)
)

CREATE TABLE FUNCIONARIO(
    FUN_COD NUMBER(4) PRIMARY KEY,
    FUN_NAME VARCHAR(30),
    COD_DEPARTAMENTO NUMBER(4)
)